/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ODTUClassPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/githubSync.ts
var import_obsidian = require("obsidian");
async function loadProcessedState(adapter) {
  const path = ".odtuclass/processed.json";
  if (await adapter.exists(path)) {
    try {
      const content = await adapter.read(path);
      return JSON.parse(content);
    } catch (e) {
      console.error("[ODTUClass] Error parsing processed.json. Returning empty state.", e);
      return {};
    }
  }
  return {};
}
async function saveProcessedState(adapter, state) {
  const path = ".odtuclass/processed.json";
  const dir = ".odtuclass";
  if (!await adapter.exists(dir)) {
    await adapter.mkdir(dir);
  }
  await adapter.write(path, JSON.stringify(state, null, 2));
}
async function syncFromGithub(plugin) {
  new import_obsidian.Notice("ODTUClass: Syncing from GitHub...");
  const owner = plugin.settings.githubOwner;
  const repo = plugin.settings.githubRepo;
  const token = plugin.settings.githubToken;
  if (!token) {
    new import_obsidian.Notice("ODTUClass: GitHub token is not set!");
    return;
  }
  const url = `https://api.github.com/repos/${owner}/${repo}/contents/.odtuclass/pending`;
  let items;
  try {
    const res = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Obsidian-ODTUClass-Plugin"
      }
    });
    if (res.status !== 200) {
      new import_obsidian.Notice(`ODTUClass: GitHub API returned status ${res.status}`);
      console.error(`[ODTUClass] GitHub API error: ${res.status}`);
      return;
    }
    items = res.json;
  } catch (e) {
    new import_obsidian.Notice("ODTUClass: Network error while fetching from GitHub.");
    console.error("[ODTUClass] GitHub fetch error:", e.message);
    return;
  }
  if (!Array.isArray(items)) {
    new import_obsidian.Notice("ODTUClass: Invalid response from GitHub API.");
    return;
  }
  const state = await loadProcessedState(plugin.app.vault.adapter);
  let createdCount = 0;
  let skipCount = 0;
  let failCount = 0;
  let stateChanged = false;
  for (const item of items) {
    if (item.name.endsWith(".json")) {
      const idStr = item.name.replace(".json", "");
      const idMatch = idStr.match(/^([a-z]+)-(\d+)-(\d+)$/);
      let possibleId = idStr;
      if (idMatch) {
        possibleId = `${idMatch[1]}:${idMatch[2]}:${idMatch[3]}`;
      }
      if (state[possibleId]) {
        skipCount++;
        continue;
      }
      try {
        const fileRes = await (0, import_obsidian.requestUrl)({
          url: item.download_url,
          method: "GET",
          headers: {
            "Authorization": `Bearer ${token}`,
            "User-Agent": "Obsidian-ODTUClass-Plugin"
          }
        });
        const data = fileRes.json;
        const realId = data.id;
        if (!realId || realId !== possibleId) {
          console.error(`[ODTUClass] Security/Consistency warning: Filename ID '${possibleId}' does not match JSON real ID '${realId}'. Skipping.`);
          failCount++;
          continue;
        }
        if (state[realId]) {
          skipCount++;
          continue;
        }
        await plugin.processAssignment(data, true);
        state[realId] = { processedAt: new Date().toISOString() };
        stateChanged = true;
        createdCount++;
      } catch (e) {
        console.error(`[ODTUClass] Error processing JSON for ${item.name}:`, e.message);
        failCount++;
      }
    }
  }
  if (stateChanged) {
    await saveProcessedState(plugin.app.vault.adapter, state);
  }
  new import_obsidian.Notice(`ODTUClass Sync: ${createdCount} created, ${skipCount} skipped, ${failCount} failed.`);
}

// src/main.ts
var DEFAULT_SETTINGS = {
  outputFolder: "ODTUClass/Assignments",
  templateFolder: "ODTUClass/Templates",
  githubOwner: "Keremdogan1",
  githubRepo: "odtuclass-sync",
  githubToken: ""
};
var ODTUClassPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "sync-from-github",
      name: "Sync from GitHub",
      callback: () => {
        syncFromGithub(this);
      }
    });
    this.addCommand({
      id: "process-pending-assignments",
      name: "Process pending assignments",
      callback: () => {
        this.processPendingAssignments();
      }
    });
    this.addSettingTab(new ODTUClassSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async processPendingAssignments() {
    const pendingDir = ".odtuclass/pending";
    const exists = await this.app.vault.adapter.exists(pendingDir);
    if (!exists) {
      new import_obsidian2.Notice("No pending ODTUClass assignments found (folder does not exist).");
      return;
    }
    const listed = await this.app.vault.adapter.list(pendingDir);
    const jsonFiles = listed.files.filter((f) => f.endsWith(".json"));
    if (jsonFiles.length === 0) {
      new import_obsidian2.Notice("No pending ODTUClass assignments found.");
      return;
    }
    let processedCount = 0;
    if (!this.app.vault.getAbstractFileByPath(this.settings.outputFolder)) {
      try {
        await this.createFolderRecursive(this.settings.outputFolder);
      } catch (e) {
        new import_obsidian2.Notice(`Failed to create output folder: ${this.settings.outputFolder}`);
        console.error(e);
        return;
      }
    }
    for (const filePath of jsonFiles) {
      try {
        const content = await this.app.vault.adapter.read(filePath);
        const assignment = JSON.parse(content);
        await this.processAssignment(assignment);
        await this.app.vault.adapter.remove(filePath);
        processedCount++;
      } catch (error) {
        console.error(`Failed to process assignment file ${filePath}:`, error);
        new import_obsidian2.Notice(`Failed to process assignment: ${filePath}. Check console for details.`);
      }
    }
    if (processedCount > 0) {
      new import_obsidian2.Notice(`Successfully processed ${processedCount} assignment(s).`);
    }
  }
  async createFolderRecursive(path) {
    const parts = path.split("/");
    let currentPath = "";
    for (const part of parts) {
      if (!part)
        continue;
      currentPath = currentPath === "" ? part : `${currentPath}/${part}`;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  async processAssignment(assignment, skipIfExists = false) {
    const templateName = this.getTemplateNameForModuleType(assignment.moduleType);
    const templatePath = `${this.settings.templateFolder}/${templateName}.md`;
    const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
    if (!templateFile || !(templateFile instanceof import_obsidian2.TFile)) {
      console.warn(`Template ${templatePath} not found for assignment ${assignment.id}.`);
      new import_obsidian2.Notice(`Template not found: ${templateName}.md`);
      throw new Error("TemplateNotFound");
    }
    const templateContent = await this.app.vault.read(templateFile);
    const renderedContent = this.renderTemplate(templateContent, assignment);
    const safeTitle = (assignment.title || "Untitled").replace(/[\\/:*?"<>|]/g, "-");
    const safeId = assignment.id.replace(/[^a-zA-Z0-9.-]/g, "-");
    const outputPath = `${this.settings.outputFolder}/${safeTitle} - ${safeId}.md`;
    const existingFile = this.app.vault.getAbstractFileByPath(outputPath);
    if (existingFile && existingFile instanceof import_obsidian2.TFile) {
      if (skipIfExists) {
        return;
      }
      await this.app.vault.modify(existingFile, renderedContent);
    } else {
      await this.app.vault.create(outputPath, renderedContent);
    }
  }
  getTemplateNameForModuleType(moduleType) {
    switch (moduleType) {
      case "assign":
      case "turnitintooltwo":
        return "Assignment";
      case "quiz":
        return "Quiz";
      case "hvp":
      case "h5pactivity":
        return "Interactive";
      default:
        return "Unknown";
    }
  }
  formatOdtuclassDate(isoString) {
    if (!isoString) {
      return { date: "", time: "" };
    }
    try {
      const dateObj = new Date(isoString);
      if (Number.isNaN(dateObj.getTime())) {
        return { date: "", time: "" };
      }
      const formatterDate = new Intl.DateTimeFormat("en-CA", {
        timeZone: "Europe/Istanbul",
        year: "numeric",
        month: "2-digit",
        day: "2-digit"
      });
      const formatterTime = new Intl.DateTimeFormat("en-GB", {
        timeZone: "Europe/Istanbul",
        hour: "2-digit",
        minute: "2-digit",
        hour12: false
      });
      return {
        date: formatterDate.format(dateObj),
        time: formatterTime.format(dateObj)
      };
    } catch (e) {
      console.warn("Invalid date format", isoString);
      return { date: "", time: "" };
    }
  }
  renderTemplate(template, assignment) {
    const open = this.formatOdtuclassDate(assignment.openAt);
    const due = this.formatOdtuclassDate(assignment.dueAt);
    const close = this.formatOdtuclassDate(assignment.closeAt);
    const data = {
      ...assignment,
      openDate: open.date,
      openTime: open.time,
      dueDate: due.date,
      dueTime: due.time,
      closeDate: close.date,
      closeTime: close.time
    };
    const placeholders = [
      "id",
      "title",
      "courseName",
      "courseId",
      "moduleId",
      "moduleType",
      "url",
      "openAt",
      "dueAt",
      "closeAt",
      "openDate",
      "openTime",
      "dueDate",
      "dueTime",
      "closeDate",
      "closeTime"
    ];
    let result = template;
    for (const p of placeholders) {
      const value = data[p] !== null && data[p] !== void 0 ? data[p] : "";
      const regex = new RegExp(`\\{\\{${p}\\}\\}`, "g");
      result = result.replace(regex, String(value));
    }
    return result;
  }
};
var ODTUClassSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ODTUClass Sync Settings" });
    new import_obsidian2.Setting(containerEl).setName("Output folder").setDesc("Folder where new assignments will be created (e.g. ODTUClass/Assignments)").addText((text) => text.setPlaceholder("ODTUClass/Assignments").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Template folder").setDesc("Folder where templates are stored (e.g. ODTUClass/Templates)").addText((text) => text.setPlaceholder("ODTUClass/Templates").setValue(this.plugin.settings.templateFolder).onChange(async (value) => {
      this.plugin.settings.templateFolder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "GitHub Sync" });
    new import_obsidian2.Setting(containerEl).setName("GitHub Owner").setDesc("GitHub username or organization (e.g. Keremdogan1)").addText((text) => text.setPlaceholder("Keremdogan1").setValue(this.plugin.settings.githubOwner).onChange(async (value) => {
      this.plugin.settings.githubOwner = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("GitHub Repository").setDesc("GitHub repository name (e.g. odtuclass-sync)").addText((text) => text.setPlaceholder("odtuclass-sync").setValue(this.plugin.settings.githubRepo).onChange(async (value) => {
      this.plugin.settings.githubRepo = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("GitHub Token (Fine-grained PAT)").setDesc("Token with Contents: Read-only access to the sync repository").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("github_pat_...").setValue(this.plugin.settings.githubToken).onChange(async (value) => {
        this.plugin.settings.githubToken = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Sync from GitHub").setDesc("Manually trigger a sync from the configured GitHub repository").addButton((button) => button.setButtonText("Sync ODTUClass").setCta().onClick(() => {
      syncFromGithub(this.plugin);
    }));
  }
};
