/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ODTUClassPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/githubSync.ts
var import_obsidian = require("obsidian");
async function loadProcessedState(adapter) {
  const path = ".odtuclass/processed.json";
  if (await adapter.exists(path)) {
    try {
      const content = await adapter.read(path);
      const cleanContent = content.replace(/^\uFEFF/, "");
      const parsed = JSON.parse(cleanContent);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        throw new Error("State is not a valid JSON object");
      }
      return parsed;
    } catch (e) {
      console.error("[ODTUClass] Error parsing processed.json:", e);
      throw new Error("Malformed processed.json");
    }
  }
  return {};
}
async function saveProcessedState(adapter, state) {
  const path = ".odtuclass/processed.json";
  const dir = ".odtuclass";
  if (!await adapter.exists(dir)) {
    await adapter.mkdir(dir);
  }
  await adapter.write(path, JSON.stringify(state, null, 2));
}
async function syncFromGithub(plugin) {
  new import_obsidian.Notice("ODTUClass: Syncing from GitHub...");
  const owner = plugin.settings.githubOwner;
  const repo = plugin.settings.githubRepo;
  const token = plugin.settings.githubToken;
  if (!token) {
    new import_obsidian.Notice("ODTUClass: GitHub token is not set!");
    return;
  }
  const url = `https://api.github.com/repos/${owner}/${repo}/contents/.odtuclass/pending`;
  let items;
  try {
    const res = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers: {
        "Authorization": `Bearer ${token}`,
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Obsidian-ODTUClass-Plugin"
      }
    });
    if (res.status !== 200) {
      new import_obsidian.Notice(`ODTUClass: GitHub API returned status ${res.status}`);
      console.error(`[ODTUClass] GitHub API error: ${res.status}`);
      return;
    }
    items = res.json;
  } catch (e) {
    new import_obsidian.Notice("ODTUClass: Network error while fetching from GitHub.");
    console.error("[ODTUClass] GitHub fetch error:", e.message);
    return;
  }
  if (!Array.isArray(items)) {
    new import_obsidian.Notice("ODTUClass: Invalid response from GitHub API.");
    return;
  }
  let state;
  try {
    state = await loadProcessedState(plugin.app.vault.adapter);
  } catch (e) {
    new import_obsidian.Notice("ODTUClass: Sync aborted! processed.json is malformed. Check console.");
    return;
  }
  let createdCount = 0;
  let skipCount = 0;
  let failCount = 0;
  let stateChanged = false;
  for (const item of items) {
    if (item.name.endsWith(".json")) {
      const idStr = item.name.replace(".json", "");
      const idMatch = idStr.match(/^([a-z]+)-(\d+)-(\d+)$/);
      let possibleId = idStr;
      if (idMatch) {
        possibleId = `${idMatch[1]}:${idMatch[2]}:${idMatch[3]}`;
      }
      const isPossibleSection = possibleId.startsWith("section:");
      if (state[possibleId] && !isPossibleSection) {
        skipCount++;
        continue;
      }
      try {
        const fileRes = await (0, import_obsidian.requestUrl)({
          url: item.download_url,
          method: "GET",
          headers: {
            "Authorization": `Bearer ${token}`,
            "User-Agent": "Obsidian-ODTUClass-Plugin"
          }
        });
        const data = fileRes.json;
        const realId = data.id;
        const sanitizedRealId = realId ? realId.replace(/[^a-zA-Z0-9._-]+/g, "-") : "";
        if (!realId || sanitizedRealId !== idStr) {
          console.error(`[ODTUClass] Security/Consistency warning: Filename ID '${idStr}' does not match JSON real ID '${realId}'. Skipping.`);
          failCount++;
          continue;
        }
        const isSection = realId.startsWith("section:");
        const existingEntry = state[realId];
        if (!isSection && existingEntry) {
          skipCount++;
          continue;
        }
        if (isSection && (existingEntry == null ? void 0 : existingEntry.contentHash) && existingEntry.contentHash === data.contentHash) {
          skipCount++;
          continue;
        }
        await plugin.processAssignment(data, true);
        state[realId] = {
          processedAt: new Date().toISOString(),
          ...isSection && data.contentHash ? { contentHash: data.contentHash } : {}
        };
        stateChanged = true;
        createdCount++;
      } catch (e) {
        console.error(`[ODTUClass] Error processing JSON for ${item.name}:`, e.message);
        failCount++;
      }
    }
  }
  if (stateChanged) {
    await saveProcessedState(plugin.app.vault.adapter, state);
  }
  new import_obsidian.Notice(`ODTUClass Sync: ${createdCount} created, ${skipCount} skipped, ${failCount} failed.`);
}

// src/main.ts
var DEFAULT_SETTINGS = {
  outputFolder: "Projects/Odt\xFCClass Tasks/_tasks",
  templateFolder: "ODTUClass/Templates",
  githubOwner: "Keremdogan1",
  githubRepo: "odtuclass-sync",
  githubToken: ""
};
var ODTUClassPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "sync-from-github",
      name: "Sync from GitHub",
      callback: () => {
        syncFromGithub(this);
      }
    });
    this.addCommand({
      id: "process-pending-assignments",
      name: "Process pending assignments",
      callback: () => {
        this.processPendingAssignments();
      }
    });
    this.addSettingTab(new ODTUClassSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async processPendingAssignments() {
    const pendingDir = ".odtuclass/pending";
    const exists = await this.app.vault.adapter.exists(pendingDir);
    if (!exists) {
      new import_obsidian2.Notice("No pending ODTUClass assignments found (folder does not exist).");
      return;
    }
    const listed = await this.app.vault.adapter.list(pendingDir);
    const jsonFiles = listed.files.filter((f) => f.endsWith(".json"));
    if (jsonFiles.length === 0) {
      new import_obsidian2.Notice("No pending ODTUClass assignments found.");
      return;
    }
    let processedCount = 0;
    if (!this.app.vault.getAbstractFileByPath(this.settings.outputFolder)) {
      try {
        await this.createFolderRecursive(this.settings.outputFolder);
      } catch (e) {
        new import_obsidian2.Notice(`Failed to create output folder: ${this.settings.outputFolder}`);
        console.error(e);
        return;
      }
    }
    for (const filePath of jsonFiles) {
      try {
        const content = await this.app.vault.adapter.read(filePath);
        const assignment = JSON.parse(content);
        await this.processAssignment(assignment);
        await this.app.vault.adapter.remove(filePath);
        processedCount++;
      } catch (error) {
        console.error(`Failed to process assignment file ${filePath}:`, error);
        new import_obsidian2.Notice(`Failed to process assignment: ${filePath}. Check console for details.`);
      }
    }
    if (processedCount > 0) {
      new import_obsidian2.Notice(`Successfully processed ${processedCount} assignment(s).`);
    }
  }
  async createFolderRecursive(path) {
    const parts = path.split("/");
    let currentPath = "";
    for (const part of parts) {
      if (!part)
        continue;
      currentPath = currentPath === "" ? part : `${currentPath}/${part}`;
      const folder = this.app.vault.getAbstractFileByPath(currentPath);
      if (!folder) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  cleanItemTitle(rawTitle, courseName, isSection, item) {
    let clean = (rawTitle || "Untitled").trim();
    if (courseName && clean.startsWith(courseName)) {
      clean = clean.slice(courseName.length).replace(/^[\s—–-]+/, "").trim();
    }
    clean = clean.replace(/^\[.*?\]\s*[^—–-]*[—–-]\s*/, "").trim();
    clean = clean.replace(/^\[.*?\]\s*/, "").trim();
    if (isSection) {
      const dateMatch = clean.match(/([a-zA-Z]+)\s+(\d{1,2})\s*[-–—]\s*(?:([a-zA-Z]+)\s+)?(\d{1,2})/);
      if (dateMatch && (clean === dateMatch[0] || clean.length <= dateMatch[0].length + 5)) {
        const secNum = (item == null ? void 0 : item.sectionNumber) || ((item == null ? void 0 : item.weekNumber) !== void 0 ? item.weekNumber : null);
        const topic = this.extractTopicFromSectionContent(item == null ? void 0 : item.content);
        if (secNum && topic) {
          return `Week ${secNum}: ${topic}`;
        } else if (topic) {
          return topic;
        } else if (secNum) {
          return `Week ${secNum}`;
        }
      }
    }
    return clean || rawTitle;
  }
  extractTopicFromSectionContent(content) {
    if (!content || typeof content !== "string")
      return null;
    const chMatch = content.match(/(?:^|\n)\s*Ch\.\s*\d+:\s*([^\n\r]+)/i);
    if (chMatch) {
      return chMatch[1].trim();
    }
    const topicsMatch = content.match(/(?:^|\n)\s*Topics to be covered:?\s*\n+([\s\S]*?)(?=\n\s*(?:Suggested problems|Reading assignment|[-*]\s*\d+\.\d+:|$))/i);
    if (topicsMatch) {
      const lines = topicsMatch[1].split("\n").map((l) => l.replace(/^\s*\d+\.\d+\.?\s*/, "").replace(/\s+and\s+Infinite\s+Limits/i, "").trim()).filter((l) => l.length > 0 && !l.startsWith("-"));
      if (lines.length > 0) {
        if (lines.length <= 2) {
          return lines.join(" & ");
        }
        return `${lines[0]} & ${lines[1]}`;
      }
    }
    return null;
  }
  async getOrCreateCourseTask(courseId, courseName) {
    const courseIdStr = String(courseId);
    const folder = this.app.vault.getAbstractFileByPath(this.settings.outputFolder);
    if (folder && folder instanceof import_obsidian2.TFolder) {
      for (const child of folder.children) {
        if (child instanceof import_obsidian2.TFile && child.extension === "md") {
          const cache = this.app.metadataCache.getFileCache(child);
          const fm = cache == null ? void 0 : cache.frontmatter;
          if (fm) {
            if (fm.id === `course:${courseIdStr}` || String(fm["odtuclass-course-id"]) === courseIdStr || fm["pm-task"] === true && fm.type === "task" && fm.title === courseName) {
              return {
                file: child,
                basename: child.basename,
                title: fm.title || courseName
              };
            }
          }
        }
      }
    }
    let cleanCourseName = courseName;
    const bracketMatch = courseName.match(/^\[(.*?)\]\s*(.*)$/);
    if (bracketMatch) {
      const codePart = bracketMatch[1].replace(/\s+All Sections/i, "").trim();
      const titlePart = bracketMatch[2].trim();
      cleanCourseName = `${codePart} - ${titlePart}`;
    }
    const safeBase = cleanCourseName.replace(/[\\/:*?"<>|]/g, "-").trim();
    const coursePath = `${this.settings.outputFolder}/${safeBase}.md`;
    let courseFile = this.app.vault.getAbstractFileByPath(coursePath);
    if (!courseFile || !(courseFile instanceof import_obsidian2.TFile)) {
      const content = `---
pm-task: true
projectId: "[[Odt\xFCClass Tasks|Odt\xFCClass Tasks]]"
id: "course:${courseIdStr}"
title: "${courseName}"
type: "task"
status: "in-progress"
priority: "medium"
due: ""
tags:
  - odtuclass
  - course
subtaskIds: []
odtuclass-course-id: "${courseIdStr}"
odtuclass-course: "${courseName}"
---

# ${courseName}

**Platform:** ODTUClass  

## Subtasks

<!-- ODTUCLASS:SUBTASKS:BEGIN -->
<!-- ODTUCLASS:SUBTASKS:END -->

## Course Notes & Workspace

- [ ] 
`;
      courseFile = await this.app.vault.create(coursePath, content);
      await this.registerCourseInProject(safeBase, courseName);
    }
    return {
      file: courseFile,
      basename: courseFile.basename,
      title: courseName
    };
  }
  async registerCourseInProject(courseBasename, courseTitle) {
    const projectPath = "Projects/Odt\xFCClass Tasks/Odt\xFCClass Tasks.md";
    const projectFile = this.app.vault.getAbstractFileByPath(projectPath);
    if (!projectFile || !(projectFile instanceof import_obsidian2.TFile))
      return;
    let content = await this.app.vault.read(projectFile);
    const courseLink = `[[${courseBasename}|${courseTitle}]]`;
    if (!content.includes(`[[${courseBasename}`)) {
      const taskIdsRegex = /^taskIds:\s*(\[[\s\S]*?\])/m;
      const taskIdsMatch = content.match(taskIdsRegex);
      if (taskIdsMatch) {
        try {
          const existingArray = JSON.parse(taskIdsMatch[1]);
          if (Array.isArray(existingArray)) {
            existingArray.push(courseLink);
            content = content.replace(taskIdsRegex, `taskIds: ${JSON.stringify(existingArray)}`);
          }
        } catch (e) {
          content = content.replace(taskIdsRegex, (match, p1) => {
            const trimmed = p1.trim().replace(/\]$/, "");
            return `taskIds: ${trimmed}, "${courseLink}"]`;
          });
        }
      }
      if (!content.includes(`- [ ] [[${courseBasename}`) && !content.includes(`- [x] [[${courseBasename}`)) {
        const tasksHeaderRegex = /(## Tasks\s*\n)/;
        if (tasksHeaderRegex.test(content)) {
          content = content.replace(tasksHeaderRegex, `$1- [ ] ${courseLink}
`);
        }
      }
      await this.app.vault.modify(projectFile, content);
    }
  }
  async linkChildToParent(parentFile, childRef) {
    let content = await this.app.vault.read(parentFile);
    const childLink = `[[${childRef.basename}|${childRef.title}]]`;
    const childEntryYaml = `  - "${childLink}"`;
    let changed = false;
    if (!content.includes(`[[${childRef.basename}`)) {
      const subtaskIdsRegex = /^subtaskIds:\s*(\[\]|.*)$/m;
      if (subtaskIdsRegex.test(content)) {
        const currentMatch = content.match(subtaskIdsRegex);
        if (currentMatch && currentMatch[1].trim() === "[]") {
          content = content.replace(subtaskIdsRegex, `subtaskIds:
${childEntryYaml}`);
        } else {
          content = content.replace(/^subtaskIds:\s*\n?/m, `subtaskIds:
${childEntryYaml}
`);
        }
      } else {
        content = content.replace(/^---\n([\s\S]*?)\n---/m, (match, p1) => {
          return `---
${p1}
subtaskIds:
${childEntryYaml}
---`;
        });
      }
      changed = true;
    }
    const subtasksBeginMarker = "<!-- ODTUCLASS:SUBTASKS:BEGIN -->";
    const subtasksEndMarker = "<!-- ODTUCLASS:SUBTASKS:END -->";
    const beginIdx = content.indexOf(subtasksBeginMarker);
    const endIdx = content.indexOf(subtasksEndMarker);
    if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
      const existingBlock = content.slice(beginIdx + subtasksBeginMarker.length, endIdx);
      if (!existingBlock.includes(`[[${childRef.basename}`)) {
        const newBlock = existingBlock.trimEnd() + `
- [ ] ${childLink}
`;
        content = content.slice(0, beginIdx + subtasksBeginMarker.length) + "\n" + newBlock.trim() + "\n" + content.slice(endIdx);
        changed = true;
      }
    } else {
      const subtasksHeader = "## Subtasks";
      const headerIdx = content.indexOf(subtasksHeader);
      if (headerIdx !== -1) {
        const afterHeader = content.slice(headerIdx + subtasksHeader.length);
        if (!afterHeader.includes(`[[${childRef.basename}`)) {
          const nextSectionMatch = afterHeader.search(/\n##\s+/);
          const insertPoint = nextSectionMatch !== -1 ? headerIdx + subtasksHeader.length + nextSectionMatch : content.length;
          const newSubtaskLine = `

- [ ] ${childLink}`;
          content = content.slice(0, insertPoint) + newSubtaskLine + content.slice(insertPoint);
          changed = true;
        }
      } else {
        const notesHeader = "## ";
        const notesIdx = content.indexOf(notesHeader);
        const subtaskBlock = `
## Subtasks

${subtasksBeginMarker}
- [ ] ${childLink}
${subtasksEndMarker}

`;
        if (notesIdx !== -1) {
          content = content.slice(0, notesIdx) + subtaskBlock + content.slice(notesIdx);
        } else {
          content += subtaskBlock;
        }
        changed = true;
      }
    }
    if (changed) {
      await this.app.vault.modify(parentFile, content);
    }
  }
  async processAssignment(assignment, skipIfExists = false) {
    var _a;
    const courseTask = await this.getOrCreateCourseTask(assignment.courseId, assignment.courseName);
    const isSection = assignment.type === "section";
    const cleanTitle = this.cleanItemTitle(assignment.title, assignment.courseName, isSection, assignment);
    const templateName = isSection ? "Section" : this.getTemplateNameForModuleType(assignment.moduleType);
    const templatePath = `${this.settings.templateFolder}/${templateName}.md`;
    const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
    if (!templateFile || !(templateFile instanceof import_obsidian2.TFile)) {
      console.warn(`Template ${templatePath} not found for assignment ${assignment.id}.`);
      new import_obsidian2.Notice(`Template not found: ${templateName}.md`);
      throw new Error("TemplateNotFound");
    }
    const templateContent = await this.app.vault.read(templateFile);
    const renderedContent = this.renderTemplate(templateContent, assignment, {
      parentFileName: courseTask.basename,
      parentTitle: courseTask.title,
      cleanTitle
    });
    const safeTitle = cleanTitle.replace(/[\\/:*?"<>|]/g, "-").trim();
    const safeId = assignment.id.replace(/[^a-zA-Z0-9.-]/g, "-");
    const outputPath = `${this.settings.outputFolder}/${safeTitle} - ${safeId}.md`;
    let existingFile = null;
    const directFile = this.app.vault.getAbstractFileByPath(outputPath);
    if (directFile && directFile instanceof import_obsidian2.TFile) {
      existingFile = directFile;
    } else {
      const folder = this.app.vault.getAbstractFileByPath(this.settings.outputFolder);
      if (folder && folder instanceof import_obsidian2.TFolder) {
        for (const child of folder.children) {
          if (child instanceof import_obsidian2.TFile && child.extension === "md") {
            if (child.basename.endsWith(`- ${safeId}`)) {
              existingFile = child;
              break;
            }
            const cache = this.app.metadataCache.getFileCache(child);
            if (((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.id) === assignment.id) {
              existingFile = child;
              break;
            }
          }
        }
      }
    }
    let targetFile;
    if (existingFile) {
      targetFile = existingFile;
      if (isSection) {
        const existingContent = await this.app.vault.read(existingFile);
        const beginMarker = "<!-- ODTUCLASS:BEGIN -->";
        const endMarker = "<!-- ODTUCLASS:END -->";
        const beginIndex = existingContent.indexOf(beginMarker);
        const endIndex = existingContent.indexOf(endMarker);
        if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
          console.warn(
            `Section file ${existingFile.path} is missing valid ODTUCLASS markers. Skipping update.`
          );
          return;
        }
        const renderedBeginIndex = renderedContent.indexOf(beginMarker);
        const renderedEndIndex = renderedContent.indexOf(endMarker);
        if (renderedBeginIndex === -1 || renderedEndIndex === -1 || renderedEndIndex < renderedBeginIndex) {
          throw new Error(
            `Section template ${templatePath} is missing valid ODTUCLASS markers.`
          );
        }
        const managedContent = renderedContent.slice(
          renderedBeginIndex + beginMarker.length,
          renderedEndIndex
        );
        let updatedContent = existingContent.slice(0, beginIndex + beginMarker.length) + managedContent + existingContent.slice(endIndex);
        const hashRegex = /^(odtuclass-hash:\s*).*$/m;
        if (hashRegex.test(updatedContent)) {
          updatedContent = updatedContent.replace(
            hashRegex,
            `$1"${assignment.contentHash || ""}"`
          );
        }
        const parentLink = `[[${courseTask.basename}|${courseTask.title}]]`;
        if (!updatedContent.match(/^parentId:\s*.*$/m)) {
          updatedContent = updatedContent.replace(/^type:\s*.*$/m, `type: "subtask"
parentId: "${parentLink}"`);
        }
        await this.app.vault.modify(existingFile, updatedContent);
        if (assignment.suggestedProblems && Array.isArray(assignment.suggestedProblems) && assignment.suggestedProblems.length > 0) {
          await this.processSubtasks(assignment, existingFile, cleanTitle);
        }
      } else {
        if (!skipIfExists) {
          let updatedContent = renderedContent;
          const existingContent = await this.app.vault.read(existingFile);
          const notesHeader = "## Description";
          if (existingContent.includes(notesHeader)) {
            const descIdx = existingContent.indexOf(notesHeader);
            const userDesc = existingContent.slice(descIdx);
            const newDescIdx = updatedContent.indexOf(notesHeader);
            if (newDescIdx !== -1) {
              updatedContent = updatedContent.slice(0, newDescIdx) + userDesc;
            }
          }
          await this.app.vault.modify(existingFile, updatedContent);
        }
      }
    } else {
      targetFile = await this.app.vault.create(outputPath, renderedContent);
      if (isSection && assignment.suggestedProblems && Array.isArray(assignment.suggestedProblems) && assignment.suggestedProblems.length > 0) {
        await this.processSubtasks(assignment, targetFile, cleanTitle);
      }
    }
    await this.linkChildToParent(courseTask.file, {
      basename: targetFile.basename,
      title: cleanTitle
    });
  }
  async processSubtasks(assignment, parentFile, parentCleanTitle) {
    var _a;
    const subtaskTemplatePath = `${this.settings.templateFolder}/Subtask.md`;
    const subtaskTemplateFile = this.app.vault.getAbstractFileByPath(subtaskTemplatePath);
    let subtaskTemplateContent = "";
    if (subtaskTemplateFile && subtaskTemplateFile instanceof import_obsidian2.TFile) {
      subtaskTemplateContent = await this.app.vault.read(subtaskTemplateFile);
    } else {
      subtaskTemplateContent = `---
pm-task: true
projectId: "[[Odt\xFCClass Tasks|Odt\xFCClass Tasks]]"
parentId: "[[{{parentFileName}}|{{parentTitle}}]]"
id: "{{id}}"
title: "{{title}}"
type: "subtask"
status: "todo"
priority: "medium"
due: "{{dueDate}}"
tags:
  - odtuclass
  - coursework
  - practice
---

Parent: [[{{parentFileName}}|{{parentTitle}}]]

## Suggested Problems (Ch. {{chapter}})

{{problemsList}}

## My Notes & Workspace

- [ ] 
`;
    }
    const parentBaseName = parentFile.basename;
    const parentTitle = parentCleanTitle || parentBaseName;
    const weekPrefixMatch = parentTitle.match(/^(Week\s+\d+)/i) || parentBaseName.match(/^(Week\s+\d+)/i);
    const weekPrefix = weekPrefixMatch ? `${weekPrefixMatch[1]} - ` : "";
    const subtaskRefs = [];
    for (const item of assignment.suggestedProblems) {
      const sectionNum = item.section;
      const topicTitle = item.title ? ` ${item.title}` : "";
      const subtaskTitle = `${sectionNum}${topicTitle} \u2014 Suggested Problems`;
      const subtaskId = `${assignment.id}:subtask:${sectionNum}`;
      const safeSubtaskTitle = subtaskTitle.replace(/[\\/:*?"<>|]/g, "-").trim();
      const fullSubtaskBasename = `${weekPrefix}${safeSubtaskTitle}`;
      const subtaskFileName = `${fullSubtaskBasename}.md`;
      const subtaskPath = `${this.settings.outputFolder}/${subtaskFileName}`;
      const problemsList = (item.problems || []).map((p) => `- [ ] Problem ${p}`).join("\n");
      const subtaskData = {
        id: subtaskId,
        title: subtaskTitle,
        parentFileName: parentBaseName,
        parentTitle,
        dueDate: assignment.weekEnd || "",
        chapter: sectionNum,
        problemsList
      };
      let renderedSubtask = subtaskTemplateContent;
      for (const key of Object.keys(subtaskData)) {
        const regex = new RegExp(`\\{\\{${key}\\}\\}`, "g");
        renderedSubtask = renderedSubtask.replace(regex, String((_a = subtaskData[key]) != null ? _a : ""));
      }
      let existingSubtask = this.app.vault.getAbstractFileByPath(subtaskPath);
      if (!existingSubtask || !(existingSubtask instanceof import_obsidian2.TFile)) {
        await this.app.vault.create(subtaskPath, renderedSubtask);
      } else {
        let subContent = await this.app.vault.read(existingSubtask);
        const expectedParent = `parentId: "[[${parentBaseName}|${parentTitle}]]"`;
        let changed = false;
        if (!subContent.includes(expectedParent)) {
          subContent = subContent.replace(/^parentId:\s*.*$/m, expectedParent);
          changed = true;
        }
        if (assignment.weekEnd && !subContent.includes(`due: "${assignment.weekEnd}"`)) {
          subContent = subContent.replace(/^due:\s*.*$/m, `due: "${assignment.weekEnd}"`);
          changed = true;
        }
        if (changed) {
          await this.app.vault.modify(existingSubtask, subContent);
        }
      }
      subtaskRefs.push({
        basename: fullSubtaskBasename,
        title: subtaskTitle
      });
    }
    if (subtaskRefs.length > 0) {
      await this.linkSubtasksInParent(parentFile, subtaskRefs);
    }
  }
  async linkSubtasksInParent(parentFile, subtaskRefs) {
    let content = await this.app.vault.read(parentFile);
    const subtaskIdsYaml = subtaskRefs.map((r) => `  - "[[${r.basename}|${r.title}]]"`).join("\n");
    const subtaskIdsRegex = /^subtaskIds:\s*(\[\]|.*)$/m;
    if (subtaskIdsRegex.test(content)) {
      content = content.replace(subtaskIdsRegex, `subtaskIds:
${subtaskIdsYaml}`);
    } else {
      content = content.replace(/^---\n([\s\S]*?)\n---/m, (match, p1) => {
        return `---
${p1}
subtaskIds:
${subtaskIdsYaml}
---`;
      });
    }
    const subtasksBeginMarker = "<!-- ODTUCLASS:SUBTASKS:BEGIN -->";
    const subtasksEndMarker = "<!-- ODTUCLASS:SUBTASKS:END -->";
    const subtasksChecklist = subtaskRefs.map((r) => {
      const isChecked = content.includes(`- [x] [[${r.basename}`);
      return `${isChecked ? "- [x]" : "- [ ]"} [[${r.basename}|${r.title}]]`;
    }).join("\n");
    const beginIdx = content.indexOf(subtasksBeginMarker);
    const endIdx = content.indexOf(subtasksEndMarker);
    if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
      content = content.slice(0, beginIdx + subtasksBeginMarker.length) + "\n" + subtasksChecklist + "\n" + content.slice(endIdx);
    } else {
      const myNotesHeader = "## My Notes & Workspace";
      const notesIdx = content.indexOf(myNotesHeader);
      const subtasksBlock = `
## Subtasks

${subtasksBeginMarker}
${subtasksChecklist}
${subtasksEndMarker}

`;
      if (notesIdx !== -1) {
        content = content.slice(0, notesIdx) + subtasksBlock + content.slice(notesIdx);
      } else {
        content += subtasksBlock;
      }
    }
    await this.app.vault.modify(parentFile, content);
  }
  getTemplateNameForModuleType(moduleType) {
    switch (moduleType) {
      case "assign":
      case "turnitintooltwo":
        return "Assignment";
      case "quiz":
        return "Quiz";
      case "hvp":
      case "h5pactivity":
        return "Interactive";
      default:
        return "Unknown";
    }
  }
  formatOdtuclassDate(isoString) {
    if (!isoString) {
      return { date: "", time: "" };
    }
    try {
      const dateObj = new Date(isoString);
      if (Number.isNaN(dateObj.getTime())) {
        return { date: "", time: "" };
      }
      const formatterDate = new Intl.DateTimeFormat("en-CA", {
        timeZone: "Europe/Istanbul",
        year: "numeric",
        month: "2-digit",
        day: "2-digit"
      });
      const formatterTime = new Intl.DateTimeFormat("en-GB", {
        timeZone: "Europe/Istanbul",
        hour: "2-digit",
        minute: "2-digit",
        hour12: false
      });
      return {
        date: formatterDate.format(dateObj),
        time: formatterTime.format(dateObj)
      };
    } catch (e) {
      console.warn("Invalid date format", isoString);
      return { date: "", time: "" };
    }
  }
  renderTemplate(template, assignment, extra) {
    const open = this.formatOdtuclassDate(assignment.openAt);
    const due = this.formatOdtuclassDate(assignment.dueAt);
    const close = this.formatOdtuclassDate(assignment.closeAt);
    const data = {
      ...assignment,
      parentFileName: (extra == null ? void 0 : extra.parentFileName) || "",
      parentTitle: (extra == null ? void 0 : extra.parentTitle) || "",
      cleanTitle: (extra == null ? void 0 : extra.cleanTitle) || assignment.title || "",
      title: (extra == null ? void 0 : extra.cleanTitle) || assignment.title || "",
      fullTitle: assignment.title || "",
      openDate: open.date,
      openTime: open.time,
      dueDate: assignment.type === "section" ? assignment.weekEnd || "" : due.date,
      dueTime: due.time,
      closeDate: close.date,
      closeTime: close.time,
      weekStart: assignment.weekStart || "",
      weekEnd: assignment.weekEnd || ""
    };
    const placeholders = [
      "id",
      "title",
      "cleanTitle",
      "fullTitle",
      "parentFileName",
      "parentTitle",
      "courseName",
      "courseId",
      "moduleId",
      "moduleType",
      "url",
      "openAt",
      "dueAt",
      "closeAt",
      "openDate",
      "openTime",
      "dueDate",
      "dueTime",
      "closeDate",
      "closeTime",
      "sectionId",
      "weekStart",
      "weekEnd",
      "content",
      "contentHash"
    ];
    let result = template;
    for (const p of placeholders) {
      const value = data[p] !== null && data[p] !== void 0 ? data[p] : "";
      const regex = new RegExp(`\\{\\{${p}\\}\\}`, "g");
      result = result.replace(regex, String(value));
    }
    return result;
  }
};
var ODTUClassSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ODTUClass Sync Settings" });
    new import_obsidian2.Setting(containerEl).setName("Output folder").setDesc("Folder where new assignments will be created (e.g. Projects/Odt\xFCClass Tasks/_tasks)").addText((text) => text.setPlaceholder("Projects/Odt\xFCClass Tasks/_tasks").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Template folder").setDesc("Folder where templates are stored (e.g. ODTUClass/Templates)").addText((text) => text.setPlaceholder("ODTUClass/Templates").setValue(this.plugin.settings.templateFolder).onChange(async (value) => {
      this.plugin.settings.templateFolder = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "GitHub Sync" });
    new import_obsidian2.Setting(containerEl).setName("GitHub Owner").setDesc("GitHub username or organization (e.g. Keremdogan1)").addText((text) => text.setPlaceholder("Keremdogan1").setValue(this.plugin.settings.githubOwner).onChange(async (value) => {
      this.plugin.settings.githubOwner = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("GitHub Repository").setDesc("GitHub repository name (e.g. odtuclass-sync)").addText((text) => text.setPlaceholder("odtuclass-sync").setValue(this.plugin.settings.githubRepo).onChange(async (value) => {
      this.plugin.settings.githubRepo = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("GitHub Token (Fine-grained PAT)").setDesc("Token with Contents: Read-only access to the sync repository").addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("github_pat_...").setValue(this.plugin.settings.githubToken).onChange(async (value) => {
        this.plugin.settings.githubToken = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Sync from GitHub").setDesc("Manually trigger a sync from the configured GitHub repository").addButton((button) => button.setButtonText("Sync ODTUClass").setCta().onClick(() => {
      syncFromGithub(this.plugin);
    }));
  }
};
